# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-21 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ScrapydClient')),
                ('ip', models.CharField(max_length=255, verbose_name='ip地址')),
                ('port', models.IntegerField(default=6800, verbose_name='端口')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('auth', models.BooleanField(default=False, verbose_name='是否授权')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='密码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Scrapyd客户端',
                'verbose_name_plural': 'Scrapyd客户端',
            },
        ),
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='部署说明')),
                ('deployed_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='部署时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='deployment.Client', verbose_name='Scrapyd客户端')),
            ],
            options={
                'verbose_name': '部署',
                'verbose_name_plural': '部署',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='项目名称')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='项目说明')),
                ('egg', models.CharField(blank=True, max_length=255, null=True)),
                ('configuration', models.TextField(blank=True, null=True, verbose_name='配置')),
                ('configurable', models.IntegerField(blank=True, default=0, verbose_name='是否配置')),
                ('built_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='打包时间')),
                ('generated_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='生成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('clients', models.ManyToManyField(through='deployment.Deploy', to='deployment.Client', verbose_name='Scrapyd客户端')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.AddField(
            model_name='deploy',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='deployment.Project', verbose_name='项目名称'),
        ),
        migrations.AlterUniqueTogether(
            name='deploy',
            unique_together=set([('client', 'project')]),
        ),
    ]
