# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-16 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0007_auto_20181021_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodictask',
            name='solar',
        ),
    ]
