# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-16 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0008_remove_periodictask_solar'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodictask',
            name='solar',
            field=models.ForeignKey(blank=True, help_text='Use a solar schedule', null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.SolarSchedule', verbose_name='solar'),
        ),
    ]
