# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-24 08:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraper', '0003_auto_20181024_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawl_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='爬取的url')),
                ('desc', models.TextField(blank=True, max_length=200, null=True, verbose_name='相关说明')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('scraper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.BaseSpider', verbose_name='爬虫实例')),
            ],
            options={
                'verbose_name': '目标链接列表',
                'verbose_name_plural': '目标链接列表',
            },
        ),
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawl_key', models.CharField(max_length=250, verbose_name='爬取关键字&&链接')),
                ('desc', models.TextField(blank=True, max_length=200, null=True, verbose_name='关键字说明')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('scraper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.BaseSpider', verbose_name='爬虫实例')),
            ],
            options={
                'verbose_name': '关键字列表',
                'verbose_name_plural': '关键字列表',
            },
        ),
        migrations.CreateModel(
            name='UrlManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='网址管理')),
                ('max_page', models.IntegerField(default=0, verbose_name='最大页码数')),
                ('url_template', models.CharField(default='', max_length=250, verbose_name='链接模板')),
                ('url_params', django_mysql.models.JSONField(blank=True, default=dict, null=True, verbose_name='链接参数')),
                ('is_add_timestamp', models.BooleanField(default=False, verbose_name='是否添加时间戳')),
                ('check_cycle', models.IntegerField(default=5, verbose_name='检查周期')),
                ('lower_threshold', models.IntegerField(default=150, verbose_name='最小阈值')),
                ('upper_threshold', models.IntegerField(default=500, verbose_name='最大阈值')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('keywords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url_tools.KeyWords', verbose_name='目标关键字')),
            ],
            options={
                'verbose_name': '网址管理',
                'verbose_name_plural': '网址管理',
            },
        ),
    ]
