# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-24 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='crawl_key',
            field=models.CharField(max_length=250, verbose_name='爬取关键字'),
        ),
    ]
