# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-24 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_tools', '0002_auto_20181024_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlmanager',
            options={'verbose_name': '链接推送管理', 'verbose_name_plural': '链接推送管理'},
        ),
        migrations.AlterField(
            model_name='urlmanager',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='链接推送管理'),
        ),
    ]
