# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-15 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('url_tools', '0003_auto_20181024_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='excellink',
            name='key_path',
            field=models.FileField(default=django.utils.timezone.now, upload_to='files/ssh_key/%Y/%m', verbose_name='文件上传'),
            preserve_default=False,
        ),
    ]
