# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-15 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_tools', '0004_excellink_key_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excellink',
            name='key_path',
            field=models.FileField(default='', upload_to='files/ssh_key/%Y/%m', verbose_name='文件上传'),
        ),
    ]
