# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-15 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_tools', '0005_auto_20181115_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excellink',
            name='key_path',
            field=models.FileField(blank=True, default='', null=True, upload_to='files/ssh_key/%Y/%m', verbose_name='文件上传'),
        ),
    ]
