# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-21 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_tools', '0007_auto_20181115_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excellink',
            name='scraper',
        ),
        migrations.RemoveField(
            model_name='keywords',
            name='scraper',
        ),
        migrations.RemoveField(
            model_name='urlmanager',
            name='keywords',
        ),
        migrations.DeleteModel(
            name='ExcelLink',
        ),
        migrations.DeleteModel(
            name='KeyWords',
        ),
        migrations.DeleteModel(
            name='UrlManager',
        ),
    ]
