# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-15 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/default.png', max_length=120, upload_to='image/%Y/%m'),
        ),
    ]
