# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-21 12:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default=None, max_length=255)),
                ('ip', models.CharField(max_length=255, verbose_name='ip地址')),
                ('port', models.IntegerField(verbose_name='端口')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('client_type', models.IntegerField(choices=[(1, 'mysql'), (2, 'mongodb'), (3, 'redis')], default=1, verbose_name='客户端类型')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='说明')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '数据库客户端',
                'verbose_name_plural': '数据库客户端',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='服务器名称')),
                ('ip', models.CharField(max_length=255, verbose_name='ip地址')),
                ('port', models.IntegerField(default=22, verbose_name='端口')),
                ('ssh_user', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('ssh_key_path', models.CharField(default='files/id_rsa', max_length=255)),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '服务器',
                'verbose_name_plural': '服务器',
            },
        ),
    ]
