# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-25 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseclient',
            name='client_name',
            field=models.CharField(default=None, max_length=255, verbose_name='客户端名称'),
        ),
        migrations.AlterField(
            model_name='databaseclient',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='databaseclient',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='用户名'),
        ),
    ]
