# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-15 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20181025_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='ssh_key_path',
            field=models.FileField(blank=True, default='', max_length=200, null=True, upload_to='files/ssh_key/%Y/%m', verbose_name='文件上传'),
        ),
    ]
