# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-15 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20181115_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='password',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='密码'),
        ),
    ]
