# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-24 01:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSpider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='爬虫名称')),
                ('website', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='网站')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='爬虫说明')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '爬虫基类',
                'verbose_name_plural': '爬虫基类',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='项目名称')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='项目说明')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='SpiderInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='详情页标题')),
                ('keyword', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='关键字')),
                ('detail_url', models.CharField(blank=True, default='', max_length=253, null=True, verbose_name='详情页链接')),
                ('scraper_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='爬取时间')),
                ('supplement', django_mysql.models.JSONField(blank=True, default=dict, null=True, verbose_name='补充字段')),
                ('version', models.DateField(auto_now=True, verbose_name='版本日期')),
            ],
            options={
                'verbose_name': '实例爬虫',
                'verbose_name_plural': '实例爬虫',
            },
        ),
        migrations.CreateModel(
            name='ECommerce',
            fields=[
                ('spiderinstance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scraper.SpiderInstance')),
                ('price', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='商品价格')),
                ('sold', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='销量')),
                ('location', models.CharField(blank=True, default='中国', max_length=100, null=True, verbose_name='地区')),
            ],
            options={
                'verbose_name': '电商爬虫',
                'verbose_name_plural': '电商爬虫',
            },
            bases=('scraper.spiderinstance',),
        ),
        migrations.AddField(
            model_name='spiderinstance',
            name='spider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.BaseSpider', verbose_name='爬虫名称'),
        ),
        migrations.AddField(
            model_name='basespider',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Project', verbose_name='项目名称'),
        ),
    ]
