# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-24 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basespider',
            options={'verbose_name': '创建爬虫', 'verbose_name_plural': '创建爬虫'},
        ),
        migrations.AlterModelOptions(
            name='ecommerce',
            options={'verbose_name': '爬虫实例(电商)', 'verbose_name_plural': '爬虫实例(电商)'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '创建项目', 'verbose_name_plural': '创建项目'},
        ),
        migrations.AlterModelOptions(
            name='spiderinstance',
            options={'verbose_name': '爬虫实例', 'verbose_name_plural': '爬虫实例'},
        ),
    ]
