# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-24 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20181024_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basespider',
            name='name',
            field=models.CharField(max_length=60, verbose_name='爬虫名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='项目名称'),
        ),
    ]
